name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ["5.0", "6.0"]

    steps:
      # Checkout the code
      - name: Git checkout
        uses: actions/checkout@v4

      # Set up Node.js based on the matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Start MongoDB based on the matrix
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Install the dependencies
      - name: Install dependencies
        run: npm install

      # Run tests with the CI environment variable
      - name: Run tests
        run: npm test
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This makes the deployment dependent on the test job passing
    if: github.ref == 'refs/heads/main'  # Only run deployment on the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setting up SSH key to access the staging server securely
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add SSH private key as GitHub Secret

      # Deploy to the staging server via SSH
      - name: Deploy to Staging
        run: |
          echo "Starting deployment to staging..."
          ssh -o StrictHostKeyChecking=no user@staging-server 'bash -s' << 'EOF'
            cd /path/to/your/app

            # Pull the latest changes from the main branch
            git fetch --all
            git reset --hard origin/main

            # Install any new dependencies
            npm install

            # Restart the application (using pm2, docker, etc.)
            pm2 restart E-BANKING-SYSTEM || pm2 start npm --name "E-BANKING-SYSTEM" -- start

            echo "Deployment completed successfully."
          EOF

      # Notify that the deployment is complete
      - name: Notify Success
        run: echo "Deployment to Staging completed successfully."
