name: MERN Stack Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Navigate to backend folder
      run: cd backend

    - name: Install backend dependencies
      run: npm install

    - name: Build backend (if necessary)
      run: npm run build || echo "No build step needed for backend"

    - name: Deploy to Azure App Service (Backend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ebank-backend
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}

  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Navigate to frontend folder
      run: cd frontend

    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Deploy to Azure App Service (Frontend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: e-bank
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
