name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ["5.0", "6.0"] # Example versions; you can adjust based on your requirements

    steps:
      # Checkout the code
      - name: Git checkout
        uses: actions/checkout@v4

      # Set up Node.js based on the matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Start MongoDB based on the matrix
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Install the dependencies
      - name: Install dependencies
        run: npm install

      # Run tests with the CI environment variable
      - name: Run tests
        run: npm test
        env:
          CI: true
