name: MERN Stack Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checout code
        uses: actions/checkout@v2

      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies for both backend and frontend
        run: npm install

      - name: Build frontend (this will build both backend and frontend based on your heroku-postbuild script)
        run: npm run heroku-postbuild

      - name: Show build log
        run: cat /home/runner/.npm/_logs/*.log

      - name: Deploy to Azure App Service (Single App Service for both backend and frontend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: e-bank
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}

      - name: Rollback on Deployment Failure
        if: failure()
        run: |
          echo "Deployment Failed, Rolling Back..."

          ssh -o StrictHostKeyChecking=no user@staging-server 'bash -s' << 'EOF'
           cd /E-Banking-System
           git reset --hard origin/main
           pm2 restart e-bank || pm2 start npm --name e-bank -- start 
          EOF
