name: MERN Stack Test, Build, and Deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build_and_deploy_staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies for both backend and frontend
        run: npm install

      - name: Build frontend (for Heroku postbuild script)
        run: npm run heroku-postbuild

      - name: Deploy to Azure App Service (Staging Environment)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ebank-backend # Use a different Azure App Service for staging
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}

      - name: Rollback on Deployment Failure (Staging)
        if: failure()
        run: |
          echo "Staging Deployment Failed, Rolling Back..."
          ssh -o StrictHostKeyChecking=no user@staging-server 'bash -s' << 'EOF'
           cd /E-Banking-System
           git reset --hard origin/staging
           pm2 restart e-bank-staging || pm2 start npm --name e-bank-staging -- start 
          EOF

  build_and_deploy_production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies for both backend and frontend
        run: npm install

      - name: Build frontend (for Heroku postbuild script)
        run: npm run heroku-postbuild

      - name: Show build log
        run: cat /home/runner/.npm/_logs/*.log

      - name: Deploy to Azure App Service (Production Environment)
        uses: azure/webapps-deploy@v2
        with:
          app-name: e-bank # Production app service
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}

      - name: Rollback on Deployment Failure (Production)
        if: failure()
        run: |
          echo "Production Deployment Failed, Rolling Back..."
          ssh -o StrictHostKeyChecking=no user@production-server 'bash -s' << 'EOF'
           cd /E-Banking-System
           git reset --hard origin/main
           pm2 restart e-bank || pm2 start npm --name e-bank -- start 
          EOF
