name: MERN Stack Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for both backend and frontend
      run: npm install

    - name: Build frontend (this will build both backend and frontend based on your heroku-postbuild script)
      run: npm run heroku-postbuild

    - name: Show build log
      run: cat /home/runner/.npm/_logs/*.log

    - name: Deploy to Azure App Service (Single App Service for both backend and frontend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: e-bank
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
